const colors = {
  light: {
    text: "#1A0A12",
    tint: "#FF3366",
    background: "#FFF5F8",
    foreground: "#1A0A12",
    card: "#FFFFFF",
    cardForeground: "#1A0A12",
    primary: "#FF3366",
    primaryForeground: "#FFFFFF",
    secondary: "#FFF0F4",
    secondaryForeground: "#1A0A12",
    muted: "#F5E6EC",
    mutedForeground: "#8A6070",
    accent: "#FF6B9D",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#F0D0DC",
    input: "#F0D0DC",
    like: "#22C55E",
    nope: "#FF3366",
    superLike: "#3B82F6",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF3366",
    background: "#0D0B12",
    foreground: "#FFFFFF",
    card: "#1A1826",
    cardForeground: "#FFFFFF",
    primary: "#FF3366",
    primaryForeground: "#FFFFFF",
    secondary: "#241F35",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1B2E",
    mutedForeground: "#9A93B3",
    accent: "#FF6B9D",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2E2840",
    input: "#2E2840",
    like: "#22C55E",
    nope: "#FF4D6D",
    superLike: "#60A5FA",
  },
  radius: 16,
};

export default colors;
